services:
  backend:
    environment:
      VITE_APP_APP_ENV: 'local'
    build:
      context: ./
    container_name: backend-dev
    restart: no
    depends_on:
      - mysql
      - redis
    ports:
      - '81:80'
    networks:
      - db
    volumes:
      - type: bind
        source: ./
        target: /var/www/backend
  mysql:
    image: 'mysql:8.4.5'
    container_name: mysql-dev
    restart: no
    networks:
      - db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'backend'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
  redis:
    image: 'redis:8.0'
    container_name: redis-dev
    restart: no
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - db
    volumes:
      - 'redis:/data'
      - './docker-storage/configs/redis.conf:/etc/redis/redis.conf'
volumes:
  mysql:
    driver: local
  redis:
    driver: local
networks:
  db:
    driver: bridge
