services:
  frontend-app:
    environment:
      VITE_APP_APP_ENV: 'local'
    build:
      context: ./frontend
    container_name: frontend-app-dev
    restart: always
    depends_on:
      - backend-app
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./frontend
        target: /var/www/frontend
  backend-app:
    environment:
      VITE_APP_APP_ENV: 'local'
    build:
      context: ./backend
    container_name: backend-app-dev
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - '81:80'
    networks:
      - db
    volumes:
      - type: bind
        source: ./backend
        target: /var/www/backend
  mysql:
    image: 'mysql:8.4.3'
    container_name: mysql-dev
    restart: always
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'backend'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
  redis:
    image: 'redis:7.4.1'
    container_name: redis-dev
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - db
    volumes:
      - 'sail-redis:/data'
      - './backend/docker-storage/configs/redis.conf:/etc/redis/redis.conf'
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
networks:
  db:
    driver: bridge
